#!/usr/bin/env python3
"""Render native Codex/Claude agents and mirror portable skills (Python 3.11+).

Canonical inputs are .agents/catalog.json, .agents/common.md, .agents/roles,
and .agents/skills. No provider calls or external writes are performed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import tomllib

MARKER = "Generated by scripts/sync_agents.py; edit canonical .agents sources."
MANIFEST = ".agents/generated-manifest.json"


def render(root: Path) -> dict[str, str]:
    catalog = json.loads((root / ".agents/catalog.json").read_text(encoding="utf-8"))
    if catalog.get("schema_version") != 1:
        raise ValueError("Unsupported catalog schema")
    common = (root / ".agents/common.md").read_text(encoding="utf-8").strip()
    output: dict[str, str] = {}
    seen: set[str] = set()
    for role in catalog["roles"]:
        name = role["name"]
        if not re.fullmatch(r"[a-z][a-z0-9-]*", name) or name in seen:
            raise ValueError(f"Invalid or duplicate role name: {name}")
        seen.add(name)
        source = (root / role["source"]).resolve()
        if not source.is_relative_to((root / ".agents/roles").resolve()):
            raise ValueError(f"Role source outside canonical directory: {source}")
        body = source.read_text(encoding="utf-8").strip()
        skill = role["skill"]
        if not (root / ".agents/skills" / skill / "SKILL.md").is_file():
            raise ValueError(f"Missing skill: {skill}")
        instructions = common + "\n\n" + body + f"\n\nPrimary workflow: `.agents/skills/{skill}/SKILL.md`."
        cx = role["codex"]
        # JSON double-quoted strings for this controlled content are valid TOML basic strings.
        fields = {"name": name, "description": role["description"],
                  "model": cx["model"], "model_reasoning_effort": cx["model_reasoning_effort"],
                  "sandbox_mode": cx["sandbox_mode"]}
        toml = "# " + MARKER + "\n" + "\n".join(f"{k} = {json.dumps(v, ensure_ascii=False)}" for k, v in fields.items()) + "\n"
        if "'''" not in instructions:
            toml += "developer_instructions = '''\n" + instructions + "\n'''\n"
        else:
            toml += "developer_instructions = " + json.dumps(instructions, ensure_ascii=False) + "\n"
        tomllib.loads(toml)
        output[f".codex/agents/{name}.toml"] = toml
        cl = role["claude"]
        front = {"name": name, "description": role["description"], "model": cl["model"],
                 "tools": cl["tools"], "permissionMode": cl["permissionMode"],
                 "maxTurns": cl["maxTurns"], "skills": [skill]}
        if cl.get("effort") is not None:
            front["effort"] = cl["effort"]
        if cl.get("isolation"):
            front["isolation"] = cl["isolation"]
            instructions += ("\n\nNative worktree note: isolation can start from the default branch rather than the assigned base. "
                             "Before edits verify the base. Only in a fresh, clean runtime-created worktree, create a unique "
                             "worker branch from the verified assigned base when needed. Never reset an existing or dirty "
                             "checkout; report an unresolved base mismatch. Resuming escalated work requires the preserved "
                             "patch/dependency commits, not just a fresh default-branch checkout.")
        # JSON scalar/flow collection encodings are accepted YAML, with no third-party dependency.
        yaml = "---\n" + "\n".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in front.items())
        output[f".claude/agents/{name}.md"] = yaml + "\n---\n\n<!-- " + MARKER + " -->\n\n" + instructions + "\n"
    for source in sorted((root / ".agents/skills").rglob("*")):
        if source.is_symlink():
            raise ValueError(f"Canonical skills must be normal files/directories: {source}")
        if source.is_file():
            rel = source.relative_to(root / ".agents/skills")
            output[(Path(".claude/skills") / rel).as_posix()] = source.read_text(encoding="utf-8")
    return output


def sync(root: Path, check: bool = False) -> list[str]:
    root = root.resolve()
    output = render(root)
    manifest_path = root / MANIFEST
    previous = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {"files": {}}
    previous_files = previous.get("files", {})
    expected = {"schema_version": 1, "files": {p: hashlib.sha256(t.encode("utf-8")).hexdigest() for p, t in sorted(output.items())}}
    manifest_text = json.dumps(expected, indent=2) + "\n"
    problems = []
    for rel, text in output.items():
        path = root / rel
        if not path.is_file() or path.read_text(encoding="utf-8") != text:
            problems.append(rel)
    stale = sorted(set(previous_files) - set(output))
    problems += ["stale:" + p for p in stale]
    if not manifest_path.exists() or manifest_path.read_text(encoding="utf-8") != manifest_text:
        problems.append(MANIFEST)
    if check:
        return problems
    # Preflight every conflict before writing any output. Never silently replace hand-edited files.
    for rel, text in output.items():
        path = root / rel
        if path.exists():
            current = path.read_text(encoding="utf-8").encode("utf-8")
            if current != text.encode("utf-8") and hashlib.sha256(current).hexdigest() != previous_files.get(rel):
                raise ValueError(f"Refusing to overwrite untracked/hand-edited native file: {rel}. Reconcile it into canonical sources first.")
    for rel in stale:
        path = (root / rel).resolve()
        if not rel.startswith((".codex/agents/", ".claude/agents/", ".claude/skills/")):
            raise ValueError(f"Unsafe stale manifest entry: {rel}")
        if not path.is_relative_to(root):
            raise ValueError(f"Path escape: {rel}")
        if path.is_file() and hashlib.sha256(path.read_text(encoding="utf-8").encode("utf-8")).hexdigest() != previous_files[rel]:
            raise ValueError(f"Refusing to remove edited stale output: {rel}")
    for rel, text in output.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    for rel in stale:
        (root / rel).unlink(missing_ok=True)
    manifest_path.write_text(manifest_text, encoding="utf-8", newline="\n")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true", help="Report missing/stale/drifted outputs without writing")
    args = parser.parse_args()
    try:
        problems = sync(args.root, args.check)
        if args.check and problems:
            print("Generated files differ:\n" + "\n".join(problems), file=sys.stderr)
            return 1
        print("Generated files are current." if args.check else "Native agent files and mirrored skills generated.")
        return 0
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Agent generation failed: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
